version: '3.8'

services:
  moss:
    image: moss:latest
    container_name: moss
    user: "1000:1000"
    ports:
      - "3000:3000"
    volumes:
      - /volume1/moss/media:/media:ro
      - /volume1/docker/moss/config:/config
      - /volume1/docker/moss/metadata:/metadata
    environment:
      - TZ=America/Denver
    restart: unless-stopped
